image: Visual Studio 2015

environment:
  NODE_PRE_GYP_GITHUB_TOKEN:
    secure: K3cebNpxFoKlym7L4fh4zabmdTCJJOPMW/7bCZENOhLGHfDXWKmC4A0FzbAxFjBw
  matrix:
    - NODEJS_VERSION: "13"
    - NODEJS_VERSION: "12"
    - NODEJS_VERSION: "10"
    - NODEJS_VERSION: "8"

install:
  - ps: Install-Product node $env:NODEJS_VERSION x64
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe -y --default-toolchain stable-x86_64-pc-windows-msvc
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - yarn
  - pushd native && cargo test --release && popd
  - ps: |
      if (-not (Test-Path env:APPVEYOR_PULL_REQUEST_NUMBER) -and ($env:APPVEYOR_REPO_TAG -eq "true")) {
        Remove-Item native\target -Recurse -Force
        yarn upload-binary 2>&1 | %{ "$_" }
        Write-Output ""
      }

build: false

cache:
  - C:\Users\appveyor\.cargo\registry
