[package]
name = "node-weakauras-parser"
version = "3.1.5"
authors = ["Velithris"]
edition = "2021"
license = "MIT"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "node_weakauras_parser"
crate-type = ["cdylib"]

[profile.release]
lto = true # increases compile time, decreases size of a binary

[build-dependencies]
neon-build = "0.8"

[dependencies]
neon = "0.8"
# neon = { version = "0.8", features = ["napi-runtime"], default-features = false } # trait Task is not implemented for napi-runtime
flate2 = { version = "1", features = ["zlib-ng"], default-features = false }
serde_json = { version = "1", features = ["preserve_order"] }
ryu = "1"
itoa = "1"
indexmap = "1"
