[package]
name = "node-weakauras-parser"
version = "3.2.0"
authors = ["Velithris"]
edition = "2021"
license = "MIT"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true # increases compile time, decreases size of a binary

[dependencies]
neon = { version = "0.10", features = ["napi-4", "promise-api", "task-api"], default-features = false }
flate2 = { version = "1", features = ["zlib-ng-compat"], default-features = false }
serde_json = { version = "1", features = ["preserve_order"] }
ryu = "1"
itoa = "1"
indexmap = "1"
