[package]
name = "node-weakauras-parser"
version = "3.0.9"
authors = ["Velithris"]
edition = "2018"
license = "MIT"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "node_weakauras_parser"
crate-type = ["cdylib"]

[profile.release]
lto = true # increases compile time, decreases size of a binary

[build-dependencies]
# neon-build = "0.4.0"
neon-build = { git = "https://github.com/neon-bindings/neon.git", rev = "20df99bedc13ee1bd7f4801a74920bd81ff099d7" }

[dependencies]
# prior to this commit, async tasks would crash the node process when using REPL:
neon = { git = "https://github.com/neon-bindings/neon.git", rev = "20df99bedc13ee1bd7f4801a74920bd81ff099d7" }
# neon = "0.4.0"
flate2 = { version = "1.0.17", features = ["zlib-ng-compat"], default-features = false }
serde_json = { version = "1.0.57", features = ["preserve_order"] }
ryu = "1.0.5"
itoa = "0.4.6"
