[package]
name = "node-weakauras-parser"
version = "3.0.11"
authors = ["Velithris"]
edition = "2018"
license = "MIT"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "node_weakauras_parser"
crate-type = ["cdylib"]

[profile.release]
lto = true # increases compile time, decreases size of a binary

[build-dependencies]
neon-build = "0.6.0"

[dependencies]
neon = "0.6.0"
# neon = { version = "0.6.0", features = ["napi-runtime"], default-features = false } # trait Task is not implemented for napi-runtime
flate2 = { version = "1.0.19", features = ["zlib-ng-compat"], default-features = false }
serde_json = { version = "1.0.61", features = ["preserve_order"] }
ryu = "1.0.5"
itoa = "0.4.7"
